POST http://localhost:4040/createAdmin
Content-Type: application/json

{
    "firstName": "Mirko",
    "lastName":"Vaccaro",
    "email":"mirko@sample.it",
    "password":"admin3456"
}

####
GET http://localhost:4040/getAdmin