POST http://localhost:4040/createAdmin
Content-Type: application/json

{
    "firstName": "Giulia",
    "lastName":"Vaccaro",
    "email":"giulia@sample.it",
    "password":"admin1234"
}

####
GET http://localhost:4040/getAdmin